services:

   postgres:
      image: postgres:16
      container_name: usuariosapi_postgres
      environment:
         POSTGRES_DB: bd_usuarios
         POSTGRES_USER: usuario_coti
         POSTGRES_PASSWORD: senha_coti
      ports:
         - "5434:5432"
      volumes:
         - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: